### ISSUE TITLE
Drop support for python 2 and python < 3.8

### ISSUE THREAD

**Issue by getzze** [Diaoul/subliminal#1071]
Dropping support for old python versions will help to clean the code and to add type annotations.

Tasks:
- [x] remove `six` from dependencies ( and replace `six.text_type` with `str`, etc. ) (#1072)
- [x] remove the `-*- coding: utf-8 -*-` lines  (#1072)
- [x] add a `pyproject.toml` file.  (#1073)
- [x] update outdated dependencies  (#1072)
- [x] repair the tests (#1074)

**Comment by ptrcnull** [comment]
this might include:
- removing `six` from dependencies ( and replacing `six.text_type` with `str`, etc. )
- removing the `-*- coding: utf-8 -*-` lines

**Comment by getzze** [comment]
also using a `pyproject.toml` file with all the relevant parameter for installing, testing and linting the files.

**Comment by getzze** [comment]
Done!
