### ISSUE TITLE
Use `main` branch with automatic linting and tests with github actions

### ISSUE THREAD

**Issue by getzze** [Diaoul/subliminal#1119]
- [x] add pre-commit config file: #1115 
- [x] fix failing checks: #1117 
- [x] add github actions: #1118 
- [ ] automatic versioning #1076 [EDITED]
- [x] move to `main` branch and drop `develop`

Next we can plan a new release :rocket:

**Comment by getzze** [comment]
Done
