### ISSUE TITLE
Next features

### ISSUE THREAD

**Issue by getzze** [Diaoul/subliminal#1130]
A list of things to improve in `subliminal` in the next (next) release, based on open issues (sorted by personal preference):

- [x] add tests for CLI (#1229) -> #1232
- [x] full core coverage -> #1211 
- [x] reorganize tests, create fake providers with fake subtitles to remove references to specific provider/refiner in test_core.py -> #1209, #1211 
- [x] make `rarfile` an optional dependency (#1096)
- [x] require a non-`hearing_impaired` subtitle (#535) -> #1175
- [x] add a second layer to sort subtitles with `hearing_impaired`, `forced`, maybe trusted uploader ?  (#925) -> #1175
- [x] add 'ignore' cli options for provider, refiner and subtitle_id  (#585, #1018, #752) -> #1160
- [x] use 3-letter language in subtitle name #1022 -> #1155
- [x] allow age filtering by creation date (#860)
- [x] scan video file for FPS, to use to match and convert subtitles (#748) -> #1154, #1206, #1212
- [x] convert subtitles to '.srt' using `pysub2` capabilities (#462, #536) -> #1207 
- [x] provide a new name for the subtitle, or for the movie, and allow specifying movie attributes (like Imdb id) #991 -> #1161
- [x] sort movie file names by alphanumeric order #1132  -> #1161
- [x] skip movies (#1053, #1023, #891)
- [x] improve verbose logging (#1059, #1133, #1164 )
- [x] add man-page #1001
- [ ] add more examples of cronjobs and helpers (#483)
- [ ] support episode without episode number, only release date. Allow no season (#692, #678)
- [ ] asynchronous providers :rocket:

**Comment by getzze** [comment]
- [ ] reorganize tests, create fake providers with fake subtitles to remove references to specific provider/refiner in `test_core.py`

**Comment by ptrcnull** [comment]
> full coverage

as long as we make sure the tests are actually meaningful, and not coverage for the sake of coverage :)

**Comment by getzze** [comment]
I think it's time to close this issue, most of the points have been solved!
