### ISSUE TITLE
Separate providers from core files

### ISSUE THREAD

**Issue by getzze** [Diaoul/subliminal#1173]
Core tests depend on providers, so these tests may break if the providers break.
Also, we could then move out the providers to another package and keep only the core library.

 - [x] add hash functions to Provider class (#1172)
 - [x] create a class for a fake provider (#1185)
 - [x] use fake providers and fake subtitles for tests (#1211)
 - [ ] ~use fake provider for doctest (#1185)~ it's ok to use vcr for doctests

**Comment by getzze** [comment]
Done with #1211
